#!/usr/bin/env python3
"""
Post-process the swagger files generated by `make swag` to inject a top-level
`tags` array (swaggo's @tag.name/@tag.description annotations are parsed but
not emitted to the spec — this script is the single source of truth for tag
order and description).

Swagger UI groups operations by the tag they carry; without a top-level
`tags` array the order falls back to first-appearance-in-paths. Declaring
the tags at the root pins the display order.

Run: python3 scripts/patch-swagger-extensions.py
     (called automatically by `make swag`)

Idempotent: an existing top-level `tags:` block is replaced in-place.
Mirrors iam-org-membership/scripts/patch-swagger-extensions.py.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent

# ---------------------------------------------------------------------------
# Tag order — edit here, re-run `make swag` to propagate.
# Order mirrors internal/adapter/inbound/http/handler files (DLG-1..7, DLG-I1..I4).
# ---------------------------------------------------------------------------

TAGS = [
    {"name": "delegations", "description": "Out-of-office delegation lifecycle — DLG-1..7 (list, create, cancel, extend, reassign, settings get/set)"},
    {"name": "internal",    "description": "Mesh-only internal API — DLG-I1..I4 (expiry sweep, review sweep, dept-delegate lookup, active-delegations escape-hatch)"},
    {"name": "infra",       "description": "Health & readiness probes + AsyncAPI viewer (unauthenticated)"},
]


# ---------------------------------------------------------------------------
# Patch swagger.json
# ---------------------------------------------------------------------------

def patch_json(path: Path) -> None:
    spec = json.loads(path.read_text())
    spec.pop("tags", None)
    ordered = {}
    for key, val in spec.items():
        if key == "securityDefinitions":
            ordered["tags"] = TAGS
        ordered[key] = val
    if "tags" not in ordered:
        ordered["tags"] = TAGS
    path.write_text(json.dumps(ordered, indent=4, ensure_ascii=False) + "\n")
    print(f"  patched {path.relative_to(ROOT)}")


# ---------------------------------------------------------------------------
# Patch swagger.yaml  (line-based insertion — avoids PyYAML dep)
# ---------------------------------------------------------------------------

def patch_yaml(path: Path) -> None:
    lines = path.read_text().splitlines()
    cleaned: list[str] = []
    skip = False
    for line in lines:
        if line.startswith("tags:"):
            skip = True
            continue
        if skip:
            if line and not line.startswith(" ") and not line.startswith("-"):
                skip = False
            else:
                continue
        cleaned.append(line)

    tag_lines = ["tags:"]
    for t in TAGS:
        tag_lines.append(f"- description: {_yaml_scalar(t['description'])}")
        tag_lines.append(f"  name: {t['name']}")

    insert_at = next(
        (i for i, l in enumerate(cleaned) if l.startswith("securityDefinitions:")),
        len(cleaned),
    )
    result = cleaned[:insert_at] + tag_lines + cleaned[insert_at:]
    path.write_text("\n".join(result) + "\n")
    print(f"  patched {path.relative_to(ROOT)}")


def _yaml_scalar(v) -> str:
    s = str(v)
    needs_quote = any(c in s for c in (':', '#', '[', ']', '{', '}', '&', '*', '!', '|', '>', "'", '"', '%', '@', '`', '\n'))
    if needs_quote:
        return '"' + s.replace('"', '\\"') + '"'
    return s


# ---------------------------------------------------------------------------
# Patch docs.go  (JSON embedded as a raw template string)
# ---------------------------------------------------------------------------

def patch_docs_go(path: Path) -> None:
    text = path.read_text()
    anchor = '"swagger": "2.0",'
    if anchor not in text:
        print(f"  WARN: anchor not found in {path.relative_to(ROOT)}, skipping", file=sys.stderr)
        return

    lines = text.splitlines()
    cleaned_lines: list[str] = []
    in_tags = False
    for line in lines:
        if line.startswith('    "tags":'):
            in_tags = True
            continue
        if in_tags:
            stripped = line.lstrip()
            if stripped.startswith('"') and line.startswith('    "') and not (
                stripped.startswith('"name":') or stripped.startswith('"description":')
            ):
                in_tags = False
            elif line.strip() in {"", "],"} or line.startswith("        "):
                if line.strip() == "],":
                    in_tags = False
                    continue
                continue
            else:
                in_tags = False
        if not in_tags:
            cleaned_lines.append(line)

    cleaned = "\n".join(cleaned_lines)

    tags_json = json.dumps(TAGS, indent=4, ensure_ascii=False)
    indented = "\n".join("    " + l for l in tags_json.splitlines())
    fragment = f'    "tags": {indented.lstrip()},'

    patched = cleaned.replace(
        f'    {anchor}',
        f'    {anchor}\n{fragment}',
        1,
    )
    if not patched.endswith("\n"):
        patched += "\n"
    path.write_text(patched)
    print(f"  patched {path.relative_to(ROOT)}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("Patching swagger tag order...")
    patch_json(ROOT / "docs/swagger/swagger.json")
    patch_yaml(ROOT / "docs/swagger/swagger.yaml")
    patch_docs_go(ROOT / "docs/swagger/docs.go")
    print("Done.")
